# 设置服务端口
server:
  port: 8081

spring:
  ##数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/wtf
    hikari:
      #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maxLifetime: 1765000
      #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      maximumPoolSize: 15
  ##模板引擎配置
  thymeleaf:
    mode: LEGACYHTML5
mybatis:
  mapperLocations: classpath:mapper/**.xml
  type-aliases-package: com.wtf.core.domain.model
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    default-executor-type: reuse
logging:
  level:
    root: error
    com:
      wtf: debug
    org:
      apache:
        ibatis: trace
      springframework: info
  config: classpath:logback-spring.xml