# 设置服务端口
server:
  port: 8083
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: spring
    password: 123456
  application:
    name: st-buyers
  redis:
    host: localhost
    port: 6379
    pool:
      max-idle: 8
      min-idle: 1
      max-active: 8
      max-wait: -1
logging:
  level:
    root: error
    com:
      wtf: debug
    org:
      apache:
        ibatis: trace
      springframework: info
  config: classpath:logback-spring.xml